# Default configuration for temporal explorator
state_mapper:
  model_url: "http://<YOUR_HOST>/v1"
  model_api_key: "<YOUR_API_KEY>"
  model_name: "Qwen/Qwen3-Coder-30B-A3B-Instruct"
  temperature: 0.7
  max_tokens: 1024
  max_retries: 5

action_selector:
  action_selection_strategy: "deterministic"

prompt_generator:
  mutator_model_url: "http://<YOUR_HOST>/v1"
  mutator_model_api_key: "<YOUR_API_KEY>"
  mutator_model_name_or_path: "Qwen/Qwen3-Coder-30B-A3B-Instruct"
  mutator_model_temperature: 0.7
  mutator_model_max_tokens: 1024
  mutator_model_max_retries: 5
