phi4m:
  model_name: microsoft/Phi-4-mini-instruct
  apis:
    - addr: http://54.212.178.87:8001/v1
      api_key: redteam233
    - addr: http://54.212.178.87:8002/v1
      api_key: redteam233

qwen3-coder:
  model_name: Qwen/Qwen3-Coder-30B-A3B-Instruct
  apis:
    - addr: http://35.87.6.13:8000/v1
      api_key: redteam233

qwen2.5-coder:
  model_name: Qwen/Qwen2.5-Coder-7B-Instruct
  apis:
    - addr: http://54.212.178.87:8010/v1
      api_key: redteam233

clm-7b:
  model_name: meta-llama/CodeLlama-7b-Instruct-hf
  apis:
    - addr: http://54.212.178.87:8011/v1
      api_key: redteam233


mistral:
  model_name: ministral-8b-instruct-2410
  apis:
    - addr: http://54.212.178.87:8012/v1
      api_key: redteam233
