
REJ_FAIL_CONFIDENCE = 99
UNF_FAIL_CONFIDENCE = 95

HACK_SUCC_CONFIDENCE = 99
SW_SUCC_CONFIDENCE = 95


JUDGE_STRONG_CONFIDENCE = 75
JUDGE_NORMAL_CONFIDENCE = 70
JUDGE_UNSURE_CONFIDENCE = 60

VUL_CODE_PADDING = "VulCodePadding"

PERFORM_GOOD = "PerformGood"
PERFORM_BAD = "PerformBad"
PERFORM_FINE = "PerformFine"